#!/bin/bash
set -e

echo "🚀 Laravel Project - Install script (generated by scaffolding-factory)"
echo "======================================================================"

# --- Docker verification (Sail) -----------------------------------------------
if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Please install it first."
    exit 1
fi

if ! docker info > /dev/null 2>&1; then
    echo "❌ Docker is not running. Please start it and run this script again."
    exit 1
fi

# --- Clean caches -----------------------------------------------------------
echo "🧹 Cleaning caches..."
rm -rf vendor node_modules bootstrap/cache storage/framework/* 2>/dev/null || true

# --- Directory permissions ----------------------------------------------------
echo "📁 Creating directories with correct permissions..."
mkdir -p bootstrap/cache storage/framework/{sessions,views,cache}
chmod -R 777 bootstrap/cache storage/framework

# --- Install PHP dependencies ------------------------------------------------
echo "📦 Installing PHP dependencies via Composer (using Docker)..."
docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v "$(pwd):/var/www/html" \
    -w /var/www/html \
    -e COMPOSER_HOME=/tmp/composer \
    laravelsail/php84-composer:latest \
    composer install --ignore-platform-reqs --no-interaction --no-scripts

# --- .env file ----------------------------------------------------------------
echo "📋 Configuring .env..."
cp -n .env.example .env 2>/dev/null || true

# --- Start Docker containers --------------------------------------------------
echo "🐳 Starting Sail containers..."
./vendor/bin/sail up -d --build

sleep 15

echo "🔑 Generating app key and storage link..."
./vendor/bin/sail artisan key:generate
./vendor/bin/sail artisan storage:link

# --- Auth Kits & Stacks -------------------------------------------------------

# --- Database Migrations ------------------------------------------------------
echo "🗄️ Running migrations..."
./vendor/bin/sail artisan migrate --force

# --- Frontend Assets ----------------------------------------------------------
echo "🎨 Installing and building frontend assets..."
./vendor/bin/sail npm install
./vendor/bin/sail npm run build

# --- Finalization -------------------------------------------------------------
echo ""
echo "✅ Setup completed successfully! 🎉"
echo ""
echo "🚀 Next steps:"
echo "   1. ./vendor/bin/sail npm run dev"
echo ""
echo "💡 For continuous development:"
echo "   - ./vendor/bin/sail up -d"
echo "   - ./vendor/bin/sail npm run dev"

